### ISSUE TITLE
CDS Annotation Failed

### ISSUE THREAD

**Issue by Ankita-1211** [xiaoli-dong/docker-metaerg#1]
Kindly excuse my less knowledge of docker & how it works but i am facing this error while running the pipeline.

Could not run command:diamond blastp -k 1 --quiet --masking 1 -p 8 -q /data/my_metaerg_output/tmp/cds.faa -d /data/db/diamond/uniprot_sprot -e 1e-05 --tmpdir /dev/shm -f 6 qseqid sseqid qlen qstart qend sstart send qframe pident bitscore evalue qcovhsp > /data/my_metaerg_output/tmp/uniprot_sprot.blasttable 2> /dev/null, No such file or directory

Perl exited with active threads:
	11 running and unjoined
	-1 finished and unjoined
	0 running and detached

Could not run command:/usr/bin/perl /NGStools/metaerg/bin/annotCDs.pl --dbdir /data/db --cpus 8 --evalue 1e-05 --identity 20 --coverage 70 --hmmcutoff --cut_ga --hmmevalue 1e-5 --outdir /data/my_metaerg_output/tmp /data/my_metaerg_output/tmp/cds.faa, No such file or directory

**Comment by xiaoli-dong** [comment]
Could you send me the Docker command to run MetaErg?

Thanks,

Xiaoli

**Comment by Ankita-1211** [comment]
Dear xiaoli

Below is the command i use to run the pipeline.
docker run --shm-size 2g -u $(id -u):$(id -g) -it -v
~/Projects/metaerg_run/data:/data/ xiaolidong/docker-metaerg metaerg.pl
--dbdir /data/db --outdir /data/my_metaerg_output /data/input.fasta
